name: csv-node-build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-project:
    name: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup in NodeJS
        uses: actions/setup-node@v1 # For init environment with nodejs
        with: 
          node-version: 12
      - name: Install dependencies
        run: yarn
      - name: Running all test
        run: yarn test