name: csv-node-build
on:
  pull_request:
    branches:
      - master
jobs:
  build-project:
    name: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Setup in NodeJS
        uses: actions/setup-node@master # For init environment with nodejs
        with: 
          strategy:
            matrix:
              node-version: [12.x]
      - name: Install dependencies
        run: yarn
      - name: Running all test
        run: yarn test