name: csv-node-build
on:
  pull_request:
    branches:
      - master
jobs:
  build-project:
    name: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Setup in NodeJS
        uses: actions/setup-node@master # For init environment with nodejs
        with: 
          node-version: 12
      - name: Install dependencies
        run: yarn install
      - name: Running all test and collect the coverage
        run: yarn test